import type {
  Statistics,
  News,
  NewsCategory,
  Achievement,
  SchoolInfo,
  Leadership,
  Teacher,
  HeroSlide,
  OrgNodeData,
} from "@/types";

// ─── Hero Slides (max 5) ───────────────────────────────────────
export const mockHeroSlides: HeroSlide[] = [
  {
    id: "slide1",
    title_km: "សូមស្វាគមន៍មកកាន់វិទ្យាល័យកំរៀង",
    title_en: "Welcome to Kamrieng High School",
    subtitle_km: "ផ្ដល់ការអប់រំ ប្រកបដោយ គុណភាព វប្បធម៌ និងនវានុវត្ត ដើម្បីអ្នកដឹកនាំ ពេលអនាគត",
    subtitle_en: "Empowering the next generation of Cambodian leaders through academic rigor, cultural integrity, and innovative learning.",
    gradient: "linear-gradient(135deg, #0d1b38 0%, #1e3a8a 55%, #1e3066 100%)",
    cta_primary_km: "ចុះឈ្មោះ",
    cta_primary_en: "Enroll Now",
    cta_secondary_km: "មើលព័ត៌មានបន្ថែម",
    cta_secondary_en: "View Prospectus",
    cta_primary_href: "/contact",
    cta_secondary_href: "/about",
    image_url: "/images/home/hero-campus-morning.png",
    sort_order: 1,
    is_active: true,
  },
  {
    id: "slide2",
    title_km: "ឆ្នើមខាងការសិក្សា",
    title_en: "Academic Excellence",
    subtitle_km: "សិស្ស ៩៦% ជោគជ័យ ក្នុងការប្រឡង BAC II ជាមួយ គ្រូបង្រៀន ដ៏ជំនាញ",
    subtitle_en: "96% of our students pass the national BAC II examination with distinction, guided by our experienced and dedicated faculty.",
    gradient: "linear-gradient(135deg, #0f2957 0%, #1e4e8c 60%, #1e40af 100%)",
    cta_primary_km: "ព័ត៌មានបន្ថែម",
    cta_primary_en: "Our Results",
    cta_secondary_km: "ទំនាក់ទំនង",
    cta_secondary_en: "Contact Us",
    cta_primary_href: "/achievements",
    cta_secondary_href: "/contact",
    image_url: "/images/home/hero-classroom-science.png",
    sort_order: 2,
    is_active: true,
  },
  {
    id: "slide3",
    title_km: "ព្រឹត្តិការណ៍ និងសកម្មភាព",
    title_en: "Vibrant School Life",
    subtitle_km: "សាលារៀននៃ ការរីកលូតលាស់ ។ ព្រឹត្តិការណ៍ ដ៏ចម្រុះ ថ្ងៃ គ្រប់ ។",
    subtitle_en: "Beyond academics, our school fosters creativity, sportsmanship, and community spirit through year-round events and activities.",
    gradient: "linear-gradient(135deg, #0a3d62 0%, #1a6b8a 50%, #0d8abe 100%)",
    cta_primary_km: "ព័ត៌មាន",
    cta_primary_en: "Latest News",
    cta_secondary_km: "ស្វែងយល់បន្ថែម",
    cta_secondary_en: "Learn More",
    cta_primary_href: "/news",
    cta_secondary_href: "/about",
    image_url: "/images/home/hero-library-reading.png",
    sort_order: 3,
    is_active: true,
  },
  {
    id: "slide4",
    title_km: "ជោគជ័យ ដ៏ក្លៀវក្លា",
    title_en: "Celebrating Achievement",
    subtitle_km: "ពានរង្វាន់ ជាតិ ខេត្ត ជិត ១០ ក្នុងមួយឆ្នាំ ។ សំណើចរ័ ។",
    subtitle_en: "Our students and faculty consistently earn national and international recognition for excellence in academics, arts, and sports.",
    gradient: "linear-gradient(135deg, #1a1a3e 0%, #2d2d7a 50%, #4a47a3 100%)",
    cta_primary_km: "ពានរង្វាន់",
    cta_primary_en: "Our Achievements",
    cta_secondary_km: "ព័ត៌មាន",
    cta_secondary_en: "Latest News",
    cta_primary_href: "/achievements",
    cta_secondary_href: "/news",
    image_url: "/images/home/hero-courtyard-friendship.png",
    sort_order: 4,
    is_active: true,
  },
  {
    id: "slide5",
    title_km: "ថ្ងៃស្អែក ចាប់ផ្ដើម នៅ ថ្ងៃ នេះ",
    title_en: "Your Future Starts Here",
    subtitle_km: "ចូលរួម ជាមួយ គ្រួសារ វិទ្យាល័យ ដ៏ជោគជ័យ ។ ផ្ទេរ ការ ចុះ ឈ្មោះ ឥឡូវ នេះ ។",
    subtitle_en: "Join our school community and take the first step toward a bright future. Admissions for the 2025–2026 academic year are now open.",
    gradient: "linear-gradient(135deg, #0d1c2f 0%, #1e3a8a 45%, #1565c0 100%)",
    cta_primary_km: "ដាក់ ពាក្យ ឥឡូវ",
    cta_primary_en: "Apply Now",
    cta_secondary_km: "ទូរស័ព្ទ មក យើង",
    cta_secondary_en: "Call Us",
    cta_primary_href: "/contact",
    cta_secondary_href: "/contact",
    image_url: "/images/home/hero-graduation-future.png",
    sort_order: 5,
    is_active: true,
  },
];

export const orgChartData: OrgNodeData = {
  id: "principal",
  name_km: "នាយកសាលា",
  name_en: "School Principal",
  icon: "ShieldCheck",
  tier: "root",
  children: [
    {
      id: "vp-academic",
      name_km: "អនុនាយក (កិច្ចការសិក្សា)",
      name_en: "Vice Principal (Academic Affairs)",
      icon: "GraduationCap",
      tier: "vice",
      children: [
        {
          id: "head-lower",
          name_km: "ប្រធានផ្នែកមធ្យមសិក្សាបឋមភូមិ",
          name_en: "Head of Lower Secondary",
          description_km: "(ថ្នាក់ទី ៧-៩)",
          description_en: "(Grades 7-9)",
          icon: "GraduationCap",
          tier: "head",
          children: [
            { id: "g7", name_km: "គ្រូបង្រៀនថ្នាក់ទី ៧", name_en: "Grade 7 Teachers", icon: "Users", tier: "leaf" },
            { id: "g8", name_km: "គ្រូបង្រៀនថ្នាក់ទី ៨", name_en: "Grade 8 Teachers", icon: "Users", tier: "leaf" },
            { id: "g9", name_km: "គ្រូបង្រៀនថ្នាក់ទី ៩", name_en: "Grade 9 Teachers", icon: "Users", tier: "leaf" },
          ],
        },
        {
          id: "head-upper",
          name_km: "ប្រធានផ្នែកមធ្យមសិក្សាទុតិយភូមិ",
          name_en: "Head of Upper Secondary",
          description_km: "(ថ្នាក់ទី ១០-១២)",
          description_en: "(Grades 10-12)",
          icon: "GraduationCap",
          tier: "head",
          children: [
            { id: "g10", name_km: "គ្រូបង្រៀនថ្នាក់ទី ១០", name_en: "Grade 10 Teachers", icon: "Users", tier: "leaf" },
            { id: "g11", name_km: "គ្រូបង្រៀនថ្នាក់ទី ១១", name_en: "Grade 11 Teachers", icon: "Users", tier: "leaf" },
            { id: "g12", name_km: "គ្រូបង្រៀនថ្នាក់ទី ១២", name_en: "Grade 12 Teachers", icon: "Users", tier: "leaf" },
          ],
        },
      ],
    },
    {
      id: "vp-admin",
      name_km: "អនុនាយក (កិច្ចការរដ្ឋបាល និងវិន័យ)",
      name_en: "Vice Principal (Administration & Student Affairs)",
      icon: "UserCog",
      tier: "vice",
      children: [
        { id: "admin-office", name_km: "ការិយាល័យរដ្ឋបាល", name_en: "Administration Office", icon: "Building2", tier: "leaf" },
        { id: "student-affairs", name_km: "កិច្ចការសិស្ស និងវិន័យ", name_en: "Student Affairs & Discipline", icon: "UserCheck", tier: "leaf" },
        { id: "facilities", name_km: "កិច្ចការអគារ និងបរិស្ថាន", name_en: "Facilities & Maintenance", icon: "Wrench", tier: "leaf" },
      ],
    },
    {
      id: "accountant",
      name_km: "គណនេយ្យករសាលា",
      name_en: "School Accountant",
      icon: "Calculator",
      tier: "vice",
    },
  ],
};

// ─── Statistics ────────────────────────────────────────────────
export const mockStats: Statistics = {
  id: "1",
  academic_year: "2024–2025",
  total_students: 2126,
  total_teachers: 51,
  total_classes: 42,
  grade_a_students: 1,
  graduation_rate: 89.3,
  pass_rate: 96,
  male_students: 1010,
  female_students: 1116,
  new_students: 187,
  is_current: true,
  created_at: "2024-09-01T00:00:00Z",
  updated_at: "2025-06-01T00:00:00Z",
};

// ─── News Categories ───────────────────────────────────────────
export const mockNewsCategories: NewsCategory[] = [
  { id: "cat1", name_km: "ការប្រកាស", name_en: "Announcement", slug: "announcement", sort_order: 1, created_at: "2024-01-01T00:00:00Z" },
  { id: "cat2", name_km: "ព្រឹត្តិការណ៍", name_en: "Events", slug: "events", sort_order: 2, created_at: "2024-01-01T00:00:00Z" },
  { id: "cat3", name_km: "វិទ្យាសាស្ត្រ", name_en: "Science", slug: "science", sort_order: 3, created_at: "2024-01-01T00:00:00Z" },
  { id: "cat4", name_km: "កីឡា", name_en: "Sports", slug: "sports", sort_order: 4, created_at: "2024-01-01T00:00:00Z" },
];

// ─── News ──────────────────────────────────────────────────────
export const mockNews: News[] = [
  {
    id: "n1",
    title_km: "វិទ្យាល័យជោគជ័យក្នុងការប្រឡងជាតិ",
    title_en: "School Achieves Outstanding National Exam Results",
    slug: "national-exam-results-2025",
    excerpt_km: "សិស្សថ្នាក់ទី១២ ចំនួន ៩៦% បានឆ្លងការប្រឡង BAC II ជាមួយនឹងលទ្ធផលល្អ",
    excerpt_en: "96% of Grade 12 students passed the national BAC II examination with excellent results this year.",
    content_km: "<p>សិស្សថ្នាក់ទី១២ ចំនួន ៩៦% បានឆ្លងការប្រឡង BAC II ជាមួយនឹងលទ្ធផលល្អ។ ស្ថិតក្នុងនោះ មានសិស្ស ៣១២ នាក់ ទទួលបានថ្នាក់ A។ ជោគជ័យនេះ គឺជាលទ្ធផលនៃការខិតខំប្រឹងប្រែង របស់សិស្ស គ្រូ និងអាណាព្យាបាល។</p>",
    content_en: "<p>A total of 96% of Grade 12 students passed the national BAC II examination with outstanding results. Among them, 312 students received Grade A honors. This achievement reflects the dedication of students, teachers, and parents alike.</p>",
    featured_image: "/images/news/new1.png",
    is_featured: true,
    status: "published",
    publish_date: "2025-06-10T00:00:00Z",
    view_count: 1240,
    category_id: "cat1",
    category: { id: "cat1", name_km: "ការប្រកាស", name_en: "Announcement", slug: "announcement", sort_order: 1, created_at: "2024-01-01T00:00:00Z" },
    created_at: "2025-06-10T00:00:00Z",
    updated_at: "2025-06-10T00:00:00Z",
  },
  {
    id: "n2",
    title_km: "ពិធីបុណ្យរំលឹកខួបកំណើតសាលា",
    title_en: "School Anniversary Celebration",
    slug: "school-anniversary-2025",
    excerpt_km: "ពិធីប្រារព្ធខួបកំណើតលើកទី ៤០ នៃវិទ្យាល័យ",
    excerpt_en: "The school celebrates its 40th anniversary with a grand ceremony attended by students, parents and distinguished guests.",
    content_km: "<p>ពិធីប្រារព្ធខួបកំណើតលើកទី ៤០ នៃវិទ្យាល័យ ត្រូវបានរៀបចំដ៏អ៊ីចឹងទ្រង់ទ្រាយ ជាមួយប្រជុំ​ ២០០០ នាក់។</p>",
    content_en: "<p>The school's 40th anniversary was celebrated grandly with more than 2,000 attendees including students, parents, alumni, and government representatives. The event featured performances, awards, and a historical exhibition.</p>",
    featured_image: "/images/news/new2.png",
    is_featured: false,
    status: "published",
    publish_date: "2025-05-20T00:00:00Z",
    view_count: 890,
    category_id: "cat2",
    category: { id: "cat2", name_km: "ព្រឹត្តិការណ៍", name_en: "Events", slug: "events", sort_order: 2, created_at: "2024-01-01T00:00:00Z" },
    created_at: "2025-05-20T00:00:00Z",
    updated_at: "2025-05-20T00:00:00Z",
  },
  {
    id: "n3",
    title_km: "សិស្សឈ្នះអូឡាំពិចគណិតអន្តរជាតិ",
    title_en: "Students Win International Math Olympiad",
    slug: "math-olympiad-win-2025",
    excerpt_km: "សិស្ស ៤ នាក់ ពីវិទ្យាល័យ ទទួលបានមេដាយមាសសៀងហៃ",
    excerpt_en: "Four students from our school won gold medals at the international mathematics olympiad held in Shanghai.",
    content_km: "<p>សិស្ស ៤ នាក់ ពីវិទ្យាល័យ ទទួលបានមេដាយមាសសៀងហៃ។ ជំនាញគណិតវិទ្យាខ្ពស់ ត្រូវបានបង្ហាញ ដ៏ច្បាស់លាស់ ។</p>",
    content_en: "<p>Four students from our school brought home gold medals from the International Mathematical Olympiad held in Shanghai, China. This remarkable achievement places our school among the top institutions in Southeast Asia for mathematics education.</p>",
    featured_image: "/images/news/new3.png",
    is_featured: true,
    status: "published",
    publish_date: "2025-04-15T00:00:00Z",
    view_count: 2100,
    category_id: "cat3",
    category: { id: "cat3", name_km: "វិទ្យាសាស្ត្រ", name_en: "Science", slug: "science", sort_order: 3, created_at: "2024-01-01T00:00:00Z" },
    created_at: "2025-04-15T00:00:00Z",
    updated_at: "2025-04-15T00:00:00Z",
  },
  {
    id: "n4",
    title_km: "ការប្រកួតបាល់ទាត់អន្តរវិទ្យាល័យ",
    title_en: "Inter-School Football Championship",
    slug: "football-championship-2025",
    excerpt_km: "ក្រុមបាល់ទាត់វិទ្យាល័យ ឈ្នះចំណាត់ថ្នាក់ទី១ ក្នុងការប្រកួតខេត្ត",
    excerpt_en: "Our school football team wins first place in the provincial inter-school championship tournament.",
    content_km: "<p>ក្រុមបាល់ទាត់វិទ្យាល័យ ឈ្នះចំណាត់ថ្នាក់ទី១ ក្នុងការប្រកួតខេត្ត ។</p>",
    content_en: "<p>Our school's football team clinched first place in the provincial inter-school championship, defeating 12 other schools. The team demonstrated exceptional teamwork and skill throughout the tournament.</p>",
    featured_image: "/images/news/new4.png",
    is_featured: false,
    status: "published",
    publish_date: "2025-03-22T00:00:00Z",
    view_count: 670,
    category_id: "cat4",
    category: { id: "cat4", name_km: "កីឡា", name_en: "Sports", slug: "sports", sort_order: 4, created_at: "2024-01-01T00:00:00Z" },
    created_at: "2025-03-22T00:00:00Z",
    updated_at: "2025-03-22T00:00:00Z",
  },
  {
    id: "n5",
    title_km: "ទស្សនកិច្ចសិក្សា ទៅប្រទេសជប៉ុន",
    title_en: "Educational Study Tour to Japan",
    slug: "japan-study-tour-2025",
    excerpt_km: "សិស្ស ៣០ នាក់ ចូលរួមក្នុងកម្មវិធីផ្លាស់ប្ដូរ វប្បធម៌ ជប៉ុន–កម្ពុជា",
    excerpt_en: "30 outstanding students participated in the Japan–Cambodia cultural exchange program in Tokyo.",
    content_km: "<p>សិស្ស ៣០ នាក់ ចូលរួមក្នុងកម្មវិធីផ្លាស់ប្ដូរ វប្បធម៌ ជប៉ុន–កម្ពុជា ។</p>",
    content_en: "<p>30 outstanding students participated in the Japan–Cambodia cultural and educational exchange program in Tokyo. They visited universities, technology companies, and cultural landmarks, enriching their global perspective.</p>",
    featured_image: "/images/news/new1.png",
    is_featured: false,
    status: "published",
    publish_date: "2025-02-10T00:00:00Z",
    view_count: 540,
    category_id: "cat2",
    category: { id: "cat2", name_km: "ព្រឹត្តិការណ៍", name_en: "Events", slug: "events", sort_order: 2, created_at: "2024-01-01T00:00:00Z" },
    created_at: "2025-02-10T00:00:00Z",
    updated_at: "2025-02-10T00:00:00Z",
  },
  {
    id: "n6",
    title_km: "ចាប់ផ្ដើមឆ្នាំសិក្សា ២០២៥–២០២៦",
    title_en: "New Academic Year 2025–2026 Opening",
    slug: "new-academic-year-2025-2026",
    excerpt_km: "វិទ្យាល័យ ស្វាគមន៍សិស្សចូលថ្មី ១៨៧ នាក់ ទៅក្នុងឆ្នាំសិក្សាថ្មី",
    excerpt_en: "The school welcomes 187 new students at the opening ceremony of the 2025–2026 academic year.",
    content_km: "<p>ឆ្នាំសិក្សា ២០២៥–២០២៦ ត្រូវបានចាប់ផ្ដើមជាផ្លូវការ ជាមួយនឹងពិធីស្វាគមន៍ ។</p>",
    content_en: "<p>The 2025–2026 academic year officially kicked off with a welcoming ceremony for 187 new students. The school's principal delivered an inspiring speech encouraging excellence and character-building throughout the year.</p>",
    featured_image: "/images/news/new2.png",
    is_featured: false,
    status: "published",
    publish_date: "2025-01-07T00:00:00Z",
    view_count: 420,
    category_id: "cat1",
    category: { id: "cat1", name_km: "ការប្រកាស", name_en: "Announcement", slug: "announcement", sort_order: 1, created_at: "2024-01-01T00:00:00Z" },
    created_at: "2025-01-07T00:00:00Z",
    updated_at: "2025-01-07T00:00:00Z",
  },
  {
    id: "n7",
    title_km: "ការប្រឡងពាក់កណ្ដាលឆ្នាំ",
    title_en: "Mid-Year Examination Schedule Released",
    slug: "mid-year-exam-schedule",
    excerpt_km: "ប្រព័ន្ធការប្រឡងពាក់កណ្ដាលឆ្នាំ ២០២៥ ត្រូវបានប្រកាស",
    excerpt_en: "The mid-year examination schedule for all grades has been officially announced.",
    content_km: "<p>ការប្រឡងពាក់កណ្ដាលឆ្នាំ ២០២៥ ត្រូវបានប្រកាស ។</p>",
    content_en: "<p>The examination schedule for the mid-year assessments has been published. All students are reminded to collect their admission cards from the administrative office before the examination week.</p>",
    is_featured: false,
    status: "published",
    publish_date: "2024-12-15T00:00:00Z",
    view_count: 780,
    category_id: "cat1",
    category: { id: "cat1", name_km: "ការប្រកាស", name_en: "Announcement", slug: "announcement", sort_order: 1, created_at: "2024-01-01T00:00:00Z" },
    created_at: "2024-12-15T00:00:00Z",
    updated_at: "2024-12-15T00:00:00Z",
  },
  {
    id: "n8",
    title_km: "ពិធីប្រគល់វិញ្ញាបនប័ត្រ",
    title_en: "Graduation Ceremony 2024",
    slug: "graduation-ceremony-2024",
    excerpt_km: "ពិធីប្រគល់វិញ្ញាបនប័ត្រសិស្សបញ្ចប់ការសិក្សា ឆ្នាំ ២០២៤",
    excerpt_en: "The 2024 graduation ceremony honours students who completed their high school education.",
    content_km: "<p>ពិធីប្រគល់វិញ្ញាបនប័ត្រ ២០២៤ ។</p>",
    content_en: "<p>The 2024 graduation ceremony was held in the school auditorium. Over 300 graduates received their diplomas in the presence of their families and school staff. The valedictorian delivered an emotional and inspiring speech.</p>",
    is_featured: false,
    status: "published",
    publish_date: "2024-11-20T00:00:00Z",
    view_count: 1560,
    category_id: "cat2",
    category: { id: "cat2", name_km: "ព្រឹត្តិការណ៍", name_en: "Events", slug: "events", sort_order: 2, created_at: "2024-01-01T00:00:00Z" },
    created_at: "2024-11-20T00:00:00Z",
    updated_at: "2024-11-20T00:00:00Z",
  },
  {
    id: "n9",
    title_km: "ផ្ទះសៀវភៅស្ដីអំពីការអប់រំ",
    title_en: "New Science Lab Equipment Installed",
    slug: "new-science-lab-equipment",
    excerpt_km: "មន្ទីរពិសោធន៍វិទ្យាសាស្ត្រ ទទួលបានបរិក្ខារថ្មី ពីអ្នកឧបត្ថម្ភ",
    excerpt_en: "The science laboratory receives new state-of-the-art equipment donated by a generous benefactor.",
    content_km: "<p>មន្ទីរពិសោធន៍វិទ្យាសាស្ត្រ ទទួលបានបរិក្ខារថ្មី ។</p>",
    content_en: "<p>Thanks to a generous donation, the school's science laboratory has been fully equipped with modern apparatus for chemistry, biology, and physics experiments. This upgrade will greatly enhance the learning experience for all science students.</p>",
    is_featured: false,
    status: "published",
    publish_date: "2024-10-05T00:00:00Z",
    view_count: 340,
    category_id: "cat3",
    category: { id: "cat3", name_km: "វិទ្យាសាស្ត្រ", name_en: "Science", slug: "science", sort_order: 3, created_at: "2024-01-01T00:00:00Z" },
    created_at: "2024-10-05T00:00:00Z",
    updated_at: "2024-10-05T00:00:00Z",
  },
];

// ─── Achievements ──────────────────────────────────────────────
export const mockAchievements: Achievement[] = [
  {
    id: "ach1",
    title_km: "មេដាយមាស ប្រឡងគណិតអន្តរជាតិ",
    title_en: "Gold Medal – International Math Olympiad",
    description_km: "សិស្ស ស្រេង ដានី ទទួលបានមេដាយមាស ក្នុងការប្រឡងគណិតអន្តរជាតិ",
    description_en: "Student Seng Dany won the gold medal at the International Mathematical Olympiad held in Shanghai.",
    achievement_type: "student",
    award_level: "national",
    achievement_date: "2025-04-15",
    participant_name: "Seng Dany",
    is_featured: true,
    status: "published",
    created_at: "2025-04-20T00:00:00Z",
    updated_at: "2025-04-20T00:00:00Z",
  },
  {
    id: "ach2",
    title_km: "ពានរង្វាន់ វិទ្យាល័យឆ្នើម ២០២៥",
    title_en: "Best School Award 2025",
    description_km: "វិទ្យាល័យ ទទួលបានពានរង្វាន់ វិទ្យាល័យឆ្នើម ថ្នាក់ខេត្ត",
    description_en: "Our school was recognized as the Best High School at the provincial level for academic excellence.",
    achievement_type: "school",
    award_level: "provincial",
    achievement_date: "2025-03-10",
    is_featured: true,
    status: "published",
    created_at: "2025-03-15T00:00:00Z",
    updated_at: "2025-03-15T00:00:00Z",
  },
  {
    id: "ach3",
    title_km: "ពានរង្វាន់ គ្រូបង្រៀនឆ្នើម",
    title_en: "Outstanding Teacher Award",
    description_km: "គ្រូ ចាន់ សុភា ទទួលបានពានរង្វាន់ គ្រូបង្រៀនឆ្នើម ថ្នាក់ជាតិ",
    description_en: "Teacher Chan Sophea received the national Outstanding Teacher Award for innovative teaching methods.",
    achievement_type: "teacher",
    award_level: "national",
    achievement_date: "2025-02-20",
    participant_name: "Chan Sophea",
    is_featured: false,
    status: "published",
    created_at: "2025-02-25T00:00:00Z",
    updated_at: "2025-02-25T00:00:00Z",
  },
  {
    id: "ach4",
    title_km: "ឈ្នះជើងឯក ការប្រកួតស្ទើរខេត្ត",
    title_en: "Provincial Football Champions",
    description_km: "ក្រុមបាល់ទាត់ ឈ្នះជើងឯក ការប្រកួតខេត្ត",
    description_en: "The school football team won the provincial championship, defeating 12 other schools.",
    achievement_type: "school",
    award_level: "provincial",
    achievement_date: "2025-03-22",
    is_featured: false,
    status: "published",
    created_at: "2025-03-25T00:00:00Z",
    updated_at: "2025-03-25T00:00:00Z",
  },
  {
    id: "ach5",
    title_km: "ទី ១ ការប្រឡងភូមិវិទ្យា",
    title_en: "1st Place – Geography Olympiad",
    description_km: "សិស្ស ហួន ស្រីនាង ទទួលបានទី ១ ក្នុងការប្រឡងភូមិវិទ្យា ថ្នាក់ខេត្ត",
    description_en: "Student Houn Srey Neang achieved first place in the provincial geography olympiad.",
    achievement_type: "student",
    award_level: "provincial",
    achievement_date: "2024-12-10",
    participant_name: "Houn Srey Neang",
    is_featured: false,
    status: "published",
    created_at: "2024-12-15T00:00:00Z",
    updated_at: "2024-12-15T00:00:00Z",
  },
  {
    id: "ach6",
    title_km: "ទទួលបានអាហារូបករណ៍ UN",
    title_en: "UN Scholarship Recipients",
    description_km: "សិស្ស ៣ នាក់ ទទួលបានអាហារូបករណ៍ UN សម្រាប់ការសិក្សានៅបរទេស",
    description_en: "Three students received UN scholarships to pursue higher education abroad.",
    achievement_type: "student",
    award_level: "national",
    achievement_date: "2024-11-05",
    is_featured: false,
    status: "published",
    created_at: "2024-11-10T00:00:00Z",
    updated_at: "2024-11-10T00:00:00Z",
  },
];

// ─── School Info ───────────────────────────────────────────────
export const mockSchoolInfo: SchoolInfo[] = [
  {
    id: "si1",
    section: "history",
    title_km: "ប្រវត្តិសាលា",
    title_en: "School History",
    content_km: "<p>វិទ្យាល័យកំរៀងត្រូវបានបង្កើតឡើងក្នុងឆ្នាំ ២០០០ តាមគំនិតផ្ដួចផ្ដើមរបស់លោក សុខ គង់ អភិបាលស្រុកកំរៀង និងលោក នូប ធឿន ប្រធានការិយាល័យអប់រំ យុវជន និងកីឡាស្រុកកំរៀង រួមជាមួយអាជ្ញាធរមូលដ្ឋាននៃស្រុកកំរៀង។ សាលាស្ថិតនៅលើផ្ទៃដី ២១,២៥៣ ម៉ែត្រការ៉េ ក្នុងភូមិអូរដា ឃុំអូរដា ស្រុកកំរៀង ខេត្តបាត់ដំបង ជិតព្រំដែនខេត្តប៉ៃលិន។</p><p>បច្ចុប្បន្នបរិវេណសាលារួមមាន អគារសិក្សាចំនួន ៥ (៥០ បន្ទប់) អគាររដ្ឋបាល និងអគារស្នាក់នៅសម្រាប់គ្រូ និងសិស្ស បម្រើដល់ថ្នាក់ទី ៧ ដល់ទី ១២។ បេសកកម្មរបស់យើងគឺពង្រីកលទ្ធភាពទទួលបានការអប់រំប្រកបដោយគុណភាពសម្រាប់កុមារនៃសហគមន៍ជនបទនេះ កសាងចំណេះដឹង និងធនធានមនុស្សដែលសិស្សរបស់យើងត្រូវការសម្រាប់អនាគតរបស់ពួកគេ ស្របតាមយុទ្ធសាស្ត្រអប់រំជាតិរបស់រាជរដ្ឋាភិបាល។</p>",
    content_en: "<p>Kamrieng High School was established in 2000, through the vision and initiative of Mr. Sok Kong, Governor of Kamrieng District, and Mr. Nub Thoeun, Head of the Kamrieng District Office of Education, Youth and Sport, together with the local authorities of Kamrieng district. The school sits on 21,253 m² of land in Ou Da village, Ou Da commune, Kamrieng district, Battambang province, near the border with Pailin province.</p><p>Today the campus includes five classroom buildings (50 classrooms), an administration building, and a dormitory for teachers and students, serving Grade 7 through Grade 12. Our mission is to expand access to quality education for the children of this rural community, building the knowledge and human resources our students need for their future, in line with the government&#x27;s national education strategy.</p>",
    sort_order: 1,
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "si2",
    section: "vision",
    title_km: "ចក្ខុវិស័យ",
    title_en: "Our Vision",
    content_km: "<p>វិទ្យាល័យកំរៀងនឹងក្លាយជាសាលាគំរូក្នុងការបណ្តុះបណ្តាលធនធានមនុស្សប្រកបដោយគុណភាព សមធម៌ និងបរិយាប័ន្ន។</p>",
    content_en: "<p>Kamrieng High School will become a model school in cultivating human resources with quality, equity, and inclusiveness.</p>",
    sort_order: 2,
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "si3",
    section: "mission",
    title_km: "បេសកកម្ម",
    title_en: "Our Mission",
    content_km: "<p>គ្រប់គ្រង និងដឹកនាំការបង្រៀន និងរៀន ហើយសហការបានល្អជាមួយភាគីពាក់ព័ន្ធទាំងអស់ ដើម្បីអភិវឌ្ឍវិទ្យាល័យកំរៀងឱ្យក្លាយជាសាលាគំរូ។</p>",
    content_en: "<p>Manage and lead teaching and learning, and cooperate well with all relevant stakeholders in order to develop Kamrieng High School into a model school.</p>",
    sort_order: 3,
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "si4",
    section: "values",
    title_km: "គុណតម្លៃស្នូល",
    title_en: "Core Values",
    content_km: "<ul><li><strong>សុច្ចរិតភាព</strong> យើងធ្វើសកម្មភាពដោយភាពស្មោះត្រង់ និងសីលធម៌។</li><li><strong>ឧត្តមភាព</strong> យើងខិតខំសម្រេចបាននូវស្តង់ដារខ្ពស់បំផុត។</li><li><strong>សេចក្តីថ្លៃថ្នូរ</strong> យើងផ្តល់តម្លៃដល់បុគ្គលម្នាក់ៗ។</li><li><strong>ការគោរពគ្នាទៅវិញទៅមក</strong> យើងផ្តល់កិត្តិយសដល់ភាពចម្រុះ។</li></ul>",
    content_en: "<ul><li><strong>Integrity</strong> We act with honesty and strong moral principles.</li><li><strong>Excellence</strong> We pursue the highest standards in everything we do.</li><li><strong>Dignity</strong> We treat everyone with honor and respect.</li><li><strong>Mutual Respect</strong> We honor diversity and value every voice.</li></ul>",
    sort_order: 4,
    updated_at: "2024-01-01T00:00:00Z",
  },
];

// ─── Leadership ────────────────────────────────────────────────
export const mockLeadership: Leadership[] = [
  {
    id: "l1",
    name_km: "អ៊ុង កន្ធារា",
    name_en: "Ung Kanputheara",
    title_km: "នាយក",
    title_en: "Principal",
    position_km: "នាយកសាលា",
    position_en: "School Principal",
    bio_km: "លោកគ្រូ អ៊ុង កន្ធារា ជានាយកសាលា មានសញ្ញាបត្រអនុបណ្ឌិតផ្នែកប្រវត្តិវិទ្យា និងបង្រៀនមុខវិជ្ជាភាសាអង់គ្លេសថ្នាក់ទី ៨ ។",
    bio_en: "Mr. Ung Kanputheara serves as the School Principal. He holds a Master's Degree in History and currently teaches English Language to Grade 8 students.",
    phone: "095 85 85 45",
    gender: "♂",
    sort_order: 1,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "l2",
    name_km: "ចាន់ ស្រីលក្ខណ៍",
    name_en: "Chan Srey Leak",
    title_km: "នាយករង",
    title_en: "Vice Principal",
    position_km: "នាយករង (ការសិក្សា)",
    position_en: "Vice Principal (Academic Affairs)",
    bio_km: "ជំនាញការ ក្នុងការកំណត់ ផែនការ​ ការ​ សិក្សា",
    bio_en: "Mrs. Srey Leak oversees curriculum development and academic planning for all grade levels.",
    photo_url: "/images/about/leader-chan-srey-leak.png",
    sort_order: 2,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "l3",
    name_km: "ហាន់ ម៉ារ៉ា",
    name_en: "Hann Mara",
    title_km: "នាយករង (កិច្ចការសិស្ស)",
    title_en: "Vice Principal (Student Affairs)",
    position_km: "នាយករង (កិច្ចការសិស្ស)",
    position_en: "Vice Principal (Student Affairs)",
    bio_km: "ទទួលខុសត្រូវ ផ្នែក​ ការ ថែទាំ​ ចំណង់ចំណូល ជំនាញ​ ប្រស​ ។",
    bio_en: "Mr. Hann Mara leads student welfare programs, discipline, and extracurricular activities.",
    photo_url: "/images/about/leader-hann-mara.png",
    sort_order: 3,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

// ─── Teachers ──────────────────────────────────────────────────
export const mockTeachers: Teacher[] = [
  // Khmer Language
  {
    id: "t1",
    name_km: "កូយ ម៉េងឡុង",
    name_en: "Koy Menglong",
    subject_km: "ភាសាខ្មែរ",
    subject_en: "Khmer Literature",
    department_km: "ផ្នែកភាសាខ្មែរ",
    department_en: "Khmer Language",
    qualification_km: "បរិញ្ញាបត្រ អក្សរសាស្ត្រខ្មែរ",
    qualification_en: "B.A. in Khmer Literature",
    photo_url: "/images/about/teachers/teacher-01.jpg",
    years_experience: 15,
    is_active: true,
    sort_order: 1,
    grade_levels: [7, 8, 9, 10, 11, 12],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "t2",
    name_km: "ឡុង ភ័ក្រ្ត",
    name_en: "Long Pheak",
    subject_km: "គណិតវិទ្យា",
    subject_en: "Mathematics",
    department_km: "ផ្នែកគណិតវិទ្យា",
    department_en: "Mathematics",
    qualification_km: "បរិញ្ញាបត្រ គណិតវិទ្យា",
    qualification_en: "B.Sc. Mathematics",
    photo_url: "/images/about/teachers/teacher-02.jpg",
    years_experience: 12,
    is_active: true,
    sort_order: 2,
    grade_levels: [7, 8, 9],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  // Sciences
  {
    id: "t3",
    name_km: "វក ឆាយ",
    name_en: "Vork Chhay",
    subject_km: "រូបវិទ្យា",
    subject_en: "Physics",
    department_km: "ផ្នែកវិទ្យាសាស្ត្រ",
    department_en: "Sciences",
    qualification_km: "អនុបណ្ឌិត រូបវិទ្យា",
    qualification_en: "M.Sc. Physics",
    photo_url: "/images/about/teachers/teacher-03.jpg",
    years_experience: 18,
    is_active: true,
    sort_order: 3,
    grade_levels: [10, 11, 12],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "t4",
    name_km: "កែវ តុញ",
    name_en: "Keav Tonh",
    subject_km: "គីមីវិទ្យា",
    subject_en: "Chemistry",
    department_km: "ផ្នែកវិទ្យាសាស្ត្រ",
    department_en: "Sciences",
    qualification_km: "បរិញ្ញាបត្រ គីមីវិទ្យា",
    qualification_en: "B.Sc. Chemistry",
    photo_url: "/images/about/teachers/teacher-04.jpg",
    years_experience: 14,
    is_active: true,
    sort_order: 4,
    grade_levels: [9, 10, 11, 12],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "t5",
    name_km: "សាន កន",
    name_en: "San Kan",
    subject_km: "ជីវវិទ្យា",
    subject_en: "Biology",
    department_km: "ផ្នែកវិទ្យាសាស្ត្រ",
    department_en: "Sciences",
    qualification_km: "បរិញ្ញាបត្រ ជីវវិទ្យា",
    qualification_en: "B.Sc. Biology",
    photo_url: "/images/about/teachers/teacher-05.jpg",
    years_experience: 9,
    is_active: true,
    sort_order: 5,
    grade_levels: [9, 10, 11, 12],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  // Social Studies
  {
    id: "t6",
    name_km: "ជា បូរី",
    name_en: "Chea Borey",
    subject_km: "ប្រវត្តិវិទ្យា",
    subject_en: "History",
    department_km: "ផ្នែកសង្គមវិទ្យា",
    department_en: "Social Studies",
    qualification_km: "បរិញ្ញាបត្រ ប្រវត្តិវិទ្យា",
    qualification_en: "B.A. History",
    photo_url: "/images/about/teachers/teacher-06.jpg",
    years_experience: 20,
    is_active: true,
    sort_order: 6,
    grade_levels: [7, 8, 9, 10, 11, 12],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "t7",
    name_km: "អាន សំអាត",
    name_en: "An Samat",
    subject_km: "ភូមិវិទ្យា",
    subject_en: "Geography",
    department_km: "ផ្នែកសង្គមវិទ្យា",
    department_en: "Social Studies",
    qualification_km: "បរិញ្ញាបត្រ ភូមិវិទ្យា",
    qualification_en: "B.A. Geography",
    photo_url: "/images/about/teachers/teacher-07.jpg",
    years_experience: 11,
    is_active: true,
    sort_order: 7,
    grade_levels: [7, 8, 9, 10, 11, 12],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  // Foreign Languages
  {
    id: "t8",
    name_km: "រិម ពន្ធា",
    name_en: "Rim Pontha",
    subject_km: "ភាសាអង់គ្លេស",
    subject_en: "English Language",
    department_km: "ផ្នែកភាសាបរទេស",
    department_en: "Foreign Languages",
    qualification_km: "អនុបណ្ឌិត ភាសាអង់គ្លេស",
    qualification_en: "M.A. English Education",
    photo_url: "/images/about/teachers/teacher-08.jpg",
    years_experience: 16,
    is_active: true,
    sort_order: 8,
    grade_levels: [7, 8, 9, 10, 11, 12],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "t9",
    name_km: "សុធា សុដ្ឋាវី",
    name_en: "Sothea Sothavi",
    subject_km: "ភាសាបារាំង",
    subject_en: "French Language",
    department_km: "ផ្នែកភាសាបរទេស",
    department_en: "Foreign Languages",
    qualification_km: "បរិញ្ញាបត្រ ភាសាបារាំង",
    qualification_en: "B.A. French",
    photo_url: "/images/about/teachers/teacher-09.jpg",
    years_experience: 8,
    is_active: true,
    sort_order: 9,
    grade_levels: [10, 11, 12],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  // Physical Education
  {
    id: "t10",
    name_km: "ណាក់ ចន្ត្រា",
    name_en: "Nak Chantrea",
    subject_km: "អប់រំកាយ",
    subject_en: "Physical Education",
    department_km: "ផ្នែកកីឡា",
    department_en: "Physical Education",
    qualification_km: "បរិញ្ញាបត្រ អប់រំកាយ",
    qualification_en: "B.Sc. Physical Education",
    photo_url: "/images/about/teachers/teacher-10.jpg",
    years_experience: 10,
    is_active: true,
    sort_order: 10,
    grade_levels: [7, 8, 9, 10, 11, 12],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  // Technology & Arts
  {
    id: "t11",
    name_km: "ឃួយ សោភ័ណ",
    name_en: "Khuoy Sopheap",
    subject_km: "បច្ចេកវិទ្យា / គណនា",
    subject_en: "ICT & Computer Science",
    department_km: "ផ្នែកបច្ចេកវិទ្យា",
    department_en: "Technology",
    qualification_km: "បរិញ្ញាបត្រ វិទ្យាសាស្ត្រកុំព្យូទ័រ",
    qualification_en: "B.Sc. Computer Science",
    photo_url: "/images/about/teachers/teacher-11.jpg",
    years_experience: 7,
    is_active: true,
    sort_order: 11,
    grade_levels: [7, 8, 9, 10, 11, 12],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "t12",
    name_km: "ឆោម ឆវន្ត",
    name_en: "Chhom Chhavann",
    subject_km: "អក្សរសិល្ប៍ខ្មែរ",
    subject_en: "Classical Khmer Literature",
    department_km: "ផ្នែកភាសាខ្មែរ",
    department_en: "Khmer Language",
    qualification_km: "បរិញ្ញាបត្រ អក្សរសាស្ត្រខ្មែរ",
    qualification_en: "B.A. in Khmer Literature",
    photo_url: "/images/about/teachers/teacher-12.jpg",
    years_experience: 13,
    is_active: true,
    sort_order: 12,
    grade_levels: [7, 8, 9, 10],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "t13",
    name_km: "ឡុង ចំរើន",
    name_en: "Long Chamroeun",
    subject_km: "គណិតវិទ្យា / ស្ថិតិ",
    subject_en: "Mathematics & Statistics",
    department_km: "ផ្នែកគណិតវិទ្យា",
    department_en: "Mathematics",
    qualification_km: "អនុបណ្ឌិត គណិតវិទ្យា",
    qualification_en: "M.Sc. Mathematics",
    photo_url: "/images/about/teachers/teacher-13.jpg",
    years_experience: 22,
    is_active: true,
    sort_order: 13,
    grade_levels: [10, 11, 12],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "t14",
    name_km: "ប៉ិល ពិរុណ",
    name_en: "Peil Pirun",
    subject_km: "សិល្បៈ / តន្ត្រី",
    subject_en: "Arts & Music",
    department_km: "ផ្នែកសិល្បៈ",
    department_en: "Arts",
    qualification_km: "បរិញ្ញាបត្រ សិល្បៈ",
    qualification_en: "B.A. Fine Arts",
    photo_url: "/images/about/teachers/teacher-14.jpg",
    years_experience: 6,
    is_active: true,
    sort_order: 14,
    grade_levels: [7, 8, 9, 10, 11, 12],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];
