-- ============================================================
-- NOTE: This migration is intentionally a no-op.
--
-- Originally it added missing columns to the `downloads` table.
-- However, the `downloads` (and `download_categories`) tables were
-- DROPPED in 004_drop_gallery_downloads.sql. The application now
-- stores downloadable files in the `documents` table created by
-- 010_create_documents_table.sql instead, so there is nothing to
-- alter here. Keeping this file (rather than deleting it) preserves
-- migration history / ordering for anyone who already applied it.
-- ============================================================
